### PR TITLE
Upgrade to checkstyle 6, sbt 0.13 and scala 2.10.3 to give Java 8 support

### PR DESCRIPTION
**Pull request by felixpageau**
@drodriguez I upgraded this package to make sure it is usable with Java 8 code. Can you please accept this commit and merge it back out of this fork?

I tested it locally with a new Play app to make sure it works well

### CODE REVIEW

**Comment by drodriguez** [comment]
I’m going to be in a plane for long hours, but initially it looks good. I will check and merge it as soon as I can. Thanks for the contribution.

**Comment by felixpageau** [comment]
Thank you. Have a good flight!

**Comment by felixpageau** [comment]
@drodriguez: Did you had a chance to check and merge this change? 

Let me know if I can do anything to help

**Comment by drodriguez** [comment]
Yes, sorry. I will merge immediately.

One question: I have latest 2.10.x is Scala 2.10.4, while the latest sbt I have is 0.13.6. Wouldn’t it be better to use those versions instead of the ones you propose? (and also we might want to check that this works with Scala 2.11.4, of course). I’m a little new to Scala, so all this version rumble is confussing.

**Pull request merged**
